---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/ci-operator/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-tracing-dev
