apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/observability-operator
  - ../../staging/base/monitoringstack
patches:
  - path: cluster-type-patch.yaml
    target:
      name: appstudio-federate-smon
      kind: ServiceMonitor
  - path: cluster-type-patch.yaml
    target:
      name: appstudio-federate-uwm-smon
      kind: ServiceMonitor
  - path: remote-write-env-details.yaml
    target:
      name: appstudio-federate-ms
      kind: MonitoringStack
  - path: monitoringstack-dev-resources-patch.yaml
    target:
      name: appstudio-federate-ms
      kind: MonitoringStack
  - path: observability-operator-dev-resources-patch.yaml
    target:
      name: cluster-observability-operator
      kind: Subscription
      group: operators.coreos.com
      version: v1alpha1
  - target:
      kind: Namespace
      name: appstudio-monitoring
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: appstudio-monitoring

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
