apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/mintmaker/config/default?ref=5f632ab7a9aabdff16092cc05127995c37c81d94
- https://github.com/konflux-ci/mintmaker/config/renovate?ref=5f632ab7a9aabdff16092cc05127995c37c81d94

namespace: mintmaker

images:
- name: quay.io/konflux-ci/mintmaker
  newName: quay.io/konflux-ci/mintmaker
  newTag: 5f632ab7a9aabdff16092cc05127995c37c81d94
- name: quay.io/konflux-ci/mintmaker-renovate-image
  newName: quay.io/konflux-ci/mintmaker-renovate-image
  newTag: eebfc799ae059998dfbc1588ed44cc81a920a8ad

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - path: manager_patch.yaml

configurations:
- kustomizeconfig.yaml
