apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - tempo-gateway-rbac.yaml
  - konflux-tracing-components.yaml
  - konflux-info.yaml
  - release-flow.yaml
patchesStrategicMerge:
  - patch-delete-external-secrets.yaml
